name: Deploy

on:
  push:
    branches: [old-site]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile
      - name: Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
        env:
          CI: false
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
